package keys

const (
	TEXT_NONE    = ""
	SUBTEXT_NONE = ""

	TEXT_SMART_INSRT    = "SMART\nINSRT"
	SUBTEXT_SMART_INSRT = "CLIP"

	TEXT_APPND    = "APPND"
	SUBTEXT_APPND = "CLIP"

	TEXT_RIPL_OWR    = "RIPL\nO/WR"
	SUBTEXT_RIPL_OWR = ""

	TEXT_CLOSE_UP    = "CLOSE\nUP"
	SUBTEXT_CLOSE_UP = "YPOS"

	TEXT_PLACE_ON_TOP    = "PLACE\nON TOP"
	SUBTEXT_PLACE_ON_TOP = ""

	TEXT_SRC_OWR    = "SRC\nO/WR"
	SUBTEXT_SRC_OWR = ""

	TEXT_IN    = "IN"
	SUBTEXT_IN = "CLR"

	TEXT_OUT    = "OUT"
	SUBTEXT_OUT = "CLR"

	TEXT_TRIM_IN    = "TRIM\nIN"
	SUBTEXT_TRIM_IN = ""

	TEXT_TRIM_OUT    = "TRIM\nOUT"
	SUBTEXT_TRIM_OUT = ""

	TEXT_ROLL    = "ROLL"
	SUBTEXT_ROLL = "SLIDE"

	TEXT_SLIP_SRC    = "SLIP\nSRC"
	SUBTEXT_SLIP_SRC = ""

	TEXT_SLIP_DEST    = "SLIP\nDEST"
	SUBTEXT_SLIP_DEST = ""

	TEXT_TRANS_DUR    = "TRANS\nDUR"
	SUBTEXT_TRANS_DUR = "SET"

	TEXT_CUT    = "CUT"
	SUBTEXT_CUT = ""

	TEXT_DIS    = "DIS"
	SUBTEXT_DIS = ""

	TEXT_SMTH_CUT    = "SMTH\nCUT"
	SUBTEXT_SMTH_CUT = ""

	TEXT_SOURCE    = "SOURCE"
	SUBTEXT_SOURCE = ""

	TEXT_TIMELINE    = "TIMELINE"
	SUBTEXT_TIMELINE = ""

	TEXT_SHTL    = "SHTL"
	SUBTEXT_SHTL = ""

	TEXT_JOG    = "JOG"
	SUBTEXT_JOG = ""

	TEXT_SCRL    = "SCRL"
	SUBTEXT_SCRL = ""

	TEXT_ESC    = "ESC"
	SUBTEXT_ESC = "UNDO"

	TEXT_SYNC_BIN    = "SYNC\nBIN"
	SUBTEXT_SYNC_BIN = ""

	TEXT_AUDIO_LEVEL    = "AUDIO\nLEVEL"
	SUBTEXT_AUDIO_LEVEL = "MARK"

	TEXT_FULL_VIEW    = "FULL\nVIEW"
	SUBTEXT_FULL_VIEW = "RVW"

	TEXT_TRANS    = "TRANS"
	SUBTEXT_TRANS = "TITLE"

	TEXT_SPLIT    = "SPLIT"
	SUBTEXT_SPLIT = "MOVE"

	TEXT_SNAP    = "SNAP"
	SUBTEXT_SNAP = "="

	TEXT_RIPL_DEL    = "RIPL\nDEL"
	SUBTEXT_RIPL_DEL = ""

	TEXT_CAM1    = "CAM\n1"
	SUBTEXT_CAM1 = ""

	TEXT_CAM2    = "CAM\n2"
	SUBTEXT_CAM2 = ""

	TEXT_CAM3    = "CAM\n3"
	SUBTEXT_CAM3 = ""

	TEXT_CAM4    = "CAM\n4"
	SUBTEXT_CAM4 = ""

	TEXT_CAM5    = "CAM\n5"
	SUBTEXT_CAM5 = ""

	TEXT_CAM6    = "CAM\n6"
	SUBTEXT_CAM6 = ""

	TEXT_CAM7    = "CAM\n7"
	SUBTEXT_CAM7 = ""

	TEXT_CAM8    = "CAM\n8"
	SUBTEXT_CAM8 = ""

	TEXT_CAM9    = "CAM\n9"
	SUBTEXT_CAM9 = ""

	TEXT_LIVE_OWR    = "LIVE\nO/WR"
	SUBTEXT_LIVE_OWR = "RND"

	TEXT_VIDEO_ONLY    = "VIDEO\nONLY"
	SUBTEXT_VIDEO_ONLY = ""

	TEXT_AUDIO_ONLY    = "AUDIO\nONLY"
	SUBTEXT_AUDIO_ONLY = ""

	TEXT_STOP_PLAY    = "STOP/PLAY"
	SUBTEXT_STOP_PLAY = ""
)
